- name: Start Velero restore for CRDs
  ansible.builtin.command: >
    {{ velero_bin_path | default('velero') }}  restore create {{ restore_name_crds }}
    --from-backup {{ backup_name_crds }}
    --include-cluster-resources=true
    --include-resources customresourcedefinitions.apiextensions.k8s.io
    {% if wait_for_restore %} --wait {% endif %}
  register: velero_restore_crds_result
  changed_when: "'completed' in velero_restore_crds_result.stdout or 'created' in velero_restore_crds_result.stdout"

- name: Show Velero restore result
  ansible.builtin.debug:
    msg: "{{ velero_restore_crds_result.stdout }}"

- name: Verify Velero restore status
  ansible.builtin.command: velero restore describe {{ restore_name_crds }}
  register: velero_restore_description
  changed_when: false

- name: Display restore description
  ansible.builtin.debug:
    msg: "{{ velero_restore_description.stdout }}"


