apiVersion: v1
kind: ConfigMap
metadata:
  name: change-storage-class-config
  namespace: velero
data:
  config: |
    version: v1
    resourceModifierRules:
    - conditions:
        groupResource: persistentvolumeclaims
        matches:
          - path: "/spec/storageClassName"
            value: "csi-default"
      patches:
        - operation: replace
          path: "/spec/storageClassName"
          value: "csi-default"
