apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-csi
provisioner: disk.csi.azure.com
parameters:
  skuName: StandardSSD_LRS   # or Premium_LRS for faster disks
  kind: Managed
  cachingMode: None
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true


