# Azure credentials and backup configuration
azure_subscription_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
azure_tenant_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
azure_client_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
azure_client_secret: "YOUR_SECRET"
azure_backup_resource_group: "velero-backup-rg"
azure_storage_account: "veleroblobstorage"
azure_blob_container: "velero-backups"
cloud_provider: 'vsphere'

# Velero versions
velero_cli_version: "v1.15.2"
azure_plugin_version: "v1.12.2"


# Resource modifier values
source_storage_class: "managed-csi"
target_storage_class: "azure-csi"
pvc_name: "pvc_name_a
match_label_app: ""
storage_class_name: "azure-csi"
resource_modifier_configmap: "change-storage-class-config"

# Velero namespaces
velero_namespace: "velero"


# Velero volumesnapshotclass
vsphere_storage_policy: "vSphere Default Storage Policy"
azure_csi_drivers:
  - { name: "azure-disk-snapshot", driver: "disk.csi.azure.com" }
  - { name: "azure-file-snapshot", driver: "file.csi.azure.com" }



# Backup/Restore names
backup_name_crds: "backup-ansible-1-vsphere"
backup_name_rbac: "backup-ansible-1-vsphere"
backup_name_workload: "backup-ansible-1-vsphere"

restore_name_crds: "restore-ansible-1-vsphere"
restore_name_rbac: "restore-ansible-1-vsphere"
restore_name_workload: "restore-ansible-1-vsphere"

# Namespaces to include/exclude in backup/restore
excluded_namespaces: "kube-system,kube-public,kube-node-lease,default,velero,cattle-system,cattle-fleet-system,fleet-default"     
included_namespaces: "test-ns1,test-ns2,velero-test"


snapshot_volumes: true
snapshot_move_data: true
wait_for_backup: true
wait_for_restore: true
async: 3600
poll: 30
