# Azure credentials and backup configuration
azure_subscription_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
azure_tenant_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
azure_client_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
azure_client_secret: "YOUR_SECRET"
azure_backup_resource_group: "velero-backup-rg"
azure_storage_account: "veleroblobstorage"
azure_blob_container: "velero-backups"
cloud_provider: 'vsphere'

# Velero versions
velero_cli_version: "v1.15.2"
azure_plugin_version: "v1.12.2"

# Cluster kubeconfig path
kubeconfig_path: "/etc/rancher/rke2/rke2.yaml"

# StorageClass names
source_storage_class: "managed-csi"
target_storage_class: "azure-csi"

# SnapshotClass names
snapshot_class_name: "velero-azure-snapshot-class"
snapshot_driver: "disk.csi.azure.com"

# Velero namespaces
velero_namespace: "velero"

# Backup/Restore names
backup_name: "backup-ansible-1-vsphere"
restore_name: "restore-ansible-1-vsphere"

# Namespaces to include/exclude in backup/restore
excluded_namespaces: "kube-system,kube-public,kube-node-lease,default,velero,cattle-system,cattle-fleet-system,fleet-default"     
included_namespaces: "test-ns1,test-ns2,velero-test"

resource_modifier_configmap: "change-storage-class-config"
storage_class_name: "storageclass"

snapshot_volumes: true
snapshot_move_data: true
wait_for_backup: true
wait_for_restore: true
