- name: Start Velero backup
  ansible.builtin.command: >
    velero backup create {{ backup_name }}
    --exclude-namespaces {{ excluded_namespaces }}
    {% if snapshot_volumes %} --snapshot-volumes {% endif %}
    {% if snapshot_move_data %} --snapshot-move-data {% endif %}
    {% if wait_for_backup %} --wait {% endif %}
  register: velero_backup_result
  changed_when: "'Backup completed' in velero_backup_result.stdout or 'created' in velero_backup_result.stdout"

- name: Show Velero backup result
  ansible.builtin.debug:
    msg: "{{ velero_backup_result.stdout }}"

- name: Verify Velero backup status
  ansible.builtin.command: velero backup describe {{ backup_name }}
  register: velero_backup_description
  changed_when: false

- name: Display backup description
  ansible.builtin.debug:
    msg: "{{ velero_backup_description.stdout }}"
