apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: velero-azure-snapshot-class  
  labels:
    velero.io/csi-volumesnapshot-class: "true"
driver: disk.csi.azure.com           
deletionPolicy: Delete               
parameters:
  incremental: "true"
