---
- name: Install Velero in Kubernetes cluster (Azure)
  hosts: localhost
  gather_facts: no
  vars:
    velero_bucket: "myvelerobackup"
    velero_resource_group: "velero-rg"
    velero_storage_account: "velerostorageacct"
    velero_subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
    velero_tenant_id: "{{ lookup('env', 'AZURE_TENANT_ID') }}"
    velero_client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
    velero_client_secret: "{{ lookup('env', 'AZURE_CLIENT_SECRET') }}"
    velero_backup_location: "azure"

  tasks:
    - name: Install Velero CLI (if missing)
      ansible.builtin.include_tasks: install_velero_cli.yml

    - name: Login to Azure
      ansible.builtin.include_tasks: azure_login.yml

    - name: Install Velero with Azure plugin
      ansible.builtin.command: >
        velero install
        --provider azure
        --plugins velero/velero-plugin-for-microsoft-azure:v1.9.0
        --bucket {{ velero_bucket }}
        --secret-file ./credentials-velero
        --backup-location-config resourceGroup={{ velero_resource_group }},storageAccount={{ velero_storage_account }}
        --use-volume-snapshots=false
        --default-volumes-to-restic
      register: velero_install_output
      changed_when: "'Velero is already installed' not in velero_install_output.stdout"

    - name: Verify Velero installation in cluster
      ansible.builtin.command: kubectl get pods -n velero
      register: velero_pods
      changed_when: false

    - name: Display Velero pods
      ansible.builtin.debug:
        msg: "{{ velero_pods.stdout_lines }}"

