- name: Install Velero CLI (if missing)
  ansible.builtin.include_tasks: install_velero_cli.yml

- name: Login to Azure
  ansible.builtin.include_tasks: azure_login.yml

- name: Install Velero with Azure plugin
  ansible.builtin.command: >
    velero install
    --provider azure 
    --plugins velero/velero-plugin-for-microsoft-azure:v{{ azure_plugin_version }}
    --bucket {{ velero_bucket }} 
    --secret-file ../../files/credentials-velero.txt 
    --backup-location-config resourceGroup={{ velero_resource_group }},storageAccount={{ velero_storage_account }},subscriptionId={{ velero_subscription_id }}
    --features=EnableCSI \
    --use-node-agent
  register: velero_install_output
  changed_when: "'Velero is already installed' not in velero_install_output.stdout"

- name: Verify Velero installation in cluster
  ansible.builtin.command: kubectl get pods -n velero
  register: velero_pods
  changed_when: false

- name: Display Velero pods
  ansible.builtin.debug:
    msg: "{{ velero_pods.stdout_lines }}"

