---
# tasks/common/install_azure.yml
# Purpose: Ensure Azure CLI is installed and available in PATH.

- name: Check if Azure CLI is already installed
  command: az version
  register: azure_cli_check
  ignore_errors: yes
  changed_when: false

- name: Install prerequisites (apt-transport-https, curl, etc.)
  apt:
    name:
      - ca-certificates
      - curl
      - apt-transport-https
      - lsb-release
      - gnupg
    state: present
    update_cache: yes
  when: azure_cli_check.rc != 0

- name: Import Microsoft signing key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  when: azure_cli_check.rc != 0

- name: Add Azure CLI APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main"
    state: present
  when: azure_cli_check.rc != 0

- name: Install Azure CLI
  apt:
    name: azure-cli
    state: present
    update_cache: yes
  when: azure_cli_check.rc != 0

- name: Verify Azure CLI installation
  command: az version
  register: azure_cli_verify
  changed_when: false

- name: Show installed Azure CLI version
  debug:
    msg: "Azure CLI installed successfully: {{ azure_cli_verify.stdout }}"

