---
- name: Set kubeconfig for SOURCE cluster
  hosts: localhost
  gather_facts: no
  vars:
    src_kubeconfig: "{{ src_kubeconfig_path }}" }}"
    kubeconfig_dest: "/home/{{ lookup('env','USER') }}/.kube/config"

  tasks:
    - name: Ensure .kube directory exists
      ansible.builtin.file:
        path: "{{ kubeconfig_dest | dirname }}"
        state: directory
        mode: '0700'

    - name: Copy source kubeconfig
      ansible.builtin.copy:
        src: "{{ src_kubeconfig }}"
        dest: "{{ kubeconfig_dest }}"
        mode: '0600'

    - name: Set environment variable for SOURCE kubeconfig
      ansible.builtin.set_environment:
        KUBECONFIG: "{{ kubeconfig_dest }}"

    - name: Verify source cluster access
      ansible.builtin.command: kubectl cluster-info
      register: src_cluster_info
      changed_when: false

    - name: Display source cluster info
      ansible.builtin.debug:
        msg: "{{ src_cluster_info.stdout }}"
i
