---
- name: Set kubeconfig for DESTINATION cluster
  hosts: localhost
  gather_facts: no
  vars:
    dest_kubeconfig: "{{ dest_kubeconfig_path }}"
    kubeconfig_dest: "/home/{{ lookup('env','USER') }}/.kube/config"

  tasks:
    - name: Ensure .kube directory exists
      ansible.builtin.file:
        path: "{{ kubeconfig_dest | dirname }}"
        state: directory
        mode: '0700'

    - name: Copy destination kubeconfig
      ansible.builtin.copy:
        src: "{{ dest_kubeconfig }}"
        dest: "{{ kubeconfig_dest }}"
        mode: '0600'

    - name: Set environment variable for DESTINATION kubeconfig
      ansible.builtin.set_environment:
        KUBECONFIG: "{{ kubeconfig_dest }}"

    - name: Verify destination cluster access
      ansible.builtin.command: kubectl cluster-info
      register: dest_cluster_info
      changed_when: false

    - name: Display destination cluster info
      ansible.builtin.debug:
        msg: "{{ dest_cluster_info.stdout }}"

