---
- name: Velero Restore Playbook
  hosts: target_cluster
  become: yes
  vars_files:
    - group_vars/all.yaml
    
  tasks:
    - name: Install Azure CLI on Azure hosts
      include_tasks: 
        file: tasks/common/install_azure.yml
        apply:
          tags: Install_Azure_CLI_on_Azure_hosts
      when: cloud_provider == 'azure'
      tags: Install_Azure_CLI_on_Azure_hosts

    - name: Install full Azure CLI setup on non Azure hosts
      include_tasks: 
        file: tasks/common/install_azure_full.yml
        apply:
          tags: Install_full_Azure_CLI_setup_on_non_Azure_hosts 
      when: cloud_provider != 'azure'
      tags: Install_full_Azure_CLI_setup_on_non_Azure_hosts

    - name: Log in to Azure
      include_tasks: tasks/common/azure_login.yml
      tags: Log_in_to_Azure
      
    - name: Install Velero CLI
      include_tasks: 
        file: tasks/common/install_velero_cli.yml
        apply:
          tags: Install_Velero_CLI
      tags: Install_Velero_CLI

    - name: Install Velero
      include_tasks:
        file: tasks/common/install_velero.yml
        apply:
          tags: Install_Velero
      tags: Install_Velero

    - name: Setup configmap
      include_tasks: 
        file: tasks/restore/setup_configmap.yml
        apply:
          tags: Setup_configmap
      tags: Setup_configmap

    - name: Velero CRDs restore
      include_tasks:
        file: tasks/restore/restore_crds.yml
        apply:
          tags: Velero_CRDs_restore
      tags: Velero_CRDs_restore

    - name: Velero cluster scoped dependencies restore
      include_tasks:
        file: tasks/restore/restore_cluster_dependencies.yml
        apply:
          tags: Velero_cluster_scoped_dependencies_restore
      tags: Velero_cluster_scoped_dependencies_restore

    - name: Velero namespaced resources restore
      include_tasks:
        file: tasks/restore/restore_namespaced_resources.yml
        apply:
          tags: Velero_namespaced_resources_restore
      tags: Velero_namespaced_resources_restore

