- name: Velero Backup Playbook
  hosts: source_cluster
  become: yes
  vars_files:
    - group_vars/all.yaml

  tasks:
    - name: Install Azure CLI on Azure hosts
      include_tasks: tasks/common/install_azure.yml
      when: cloud_provider == 'azure'
      tags: Install_Azure_CLI_on_Azure_hosts

    - name: Install full Azure CLI setup on non-Azure hosts
      include_tasks: tasks/common/install_azure_full.yml
      when: cloud_provider != 'azure'
      tags: Install_full_Azure_CLI_setup_on_non-Azure_hosts

    - name: Log in to Azure
      include_tasks: tasks/common/azure_login.yml
      tags: Log_in_to_Azure
      
    - name: Set KUBECONFIG
      include_tasks: tasks/common/set_kubeconfig_src.yml
      tags: Set_KUBECONFIG
      
    - name: Install Velero CLI
      include_tasks: tasks/common/install_velero.yml
      tags: Install_Velero_CLI

    - name: Install Velero
      include_tasks: tasks/common/install_velero.yml
      tags: Install_Velero

    - name: Setup snapshot class for Velero
      include_tasks: tasks/backup/setup_snapshotclass.yml
      tags: Setup_snapshot_class_for_Velero

    - name: Create Velero backup
      include_tasks: tasks/backup/create_backup.yml
      tags: Create_Velero_backup


