---
- name: Velero Restore Playbook
  hosts: target_cluster
  become: yes
  vars_files:
    - group_vars/all.yml

  tasks:
    - include_tasks: tasks/common/install_azure.yml
    - include_tasks: tasks/common/install_velero.yml
    - include_tasks: tasks/common/set_kubeconfig.yml
    - include_tasks: tasks/common/azure_login.yml

    - include_tasks: tasks/restore/setup_storageclass.yml
      when: ansible_facts['cloud_provider'] == 'azure'
    - include_tasks: tasks/restore/setup_configmap.yml
    - include_tasks: tasks/restore/create_restore.yml

