- name: Velero Backup Playbook
  hosts: source_cluster
  become: yes
  gather_facts: no
  vars_files:
    - group_vars/all.yaml
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
    PATH: "{{ ansible_env.PATH }}:/var/lib/rancher/rke2/bin"

  tasks:
    - name: Install Azure CLI on Azure hosts
      include_tasks: tasks/common/install_azure.yml
      when: cloud_provider == 'azure'
      tags: Install_Azure_CLI_on_Azure_hosts

    - name: Install full Azure CLI setup on non-Azure hosts
      include_tasks: tasks/common/install_azure_full.yml
      when: cloud_provider != 'azure'
      tags: Install_full_Azure_CLI_setup_on_non-Azure_hosts

    - name: Log in to Azure
      include_tasks: tasks/common/azure_login.yml
      tags: Log_in_to_Azure

    - name: Install Velero CLI
      include_tasks: tasks/common/install_velero.yml
      tags: Install_Velero_CLI

    - name: Install Velero
      include_tasks:
        file: tasks/common/install_velero.yml
        apply:
          tags: Install_Velero
      tags: Install_Velero

    - name: Setup snapshot class for Velero
      include_tasks:
        file: tasks/backup/setup_snapshotclass.yml
        apply:
          tags: Setup_snapshot_class_for_Velero
      tags: Setup_snapshot_class_for_Velero

    - name: Create Velero backup
      include_tasks:
        file: tasks/backup/create_backup.yml
        apply:
          tags: Create_Velero_backup
      tags: Create_Velero_backup

