- name: Velero Backup Playbook
  hosts: source_cluster
  become: yes
  vars_files:
    - group_vars/all.yml

  tasks:
    - name: Install Azure CLI on Azure hosts
      include_tasks: tasks/common/install_azure.yml
      when: ansible_facts['cloud_provider'] == 'azure'

    - name: Install full Azure CLI setup on non-Azure hosts
      include_tasks: tasks/common/install_azure_full.yml
      when: ansible_facts['cloud_provider'] != 'azure'

    - name: Install Velero CLI
      include_tasks: tasks/common/install_velero.yml

    - name: Set kubeconfig for source cluster
      include_tasks: tasks/common/set_kubeconfig.yml

    - name: Log in to Azure
      include_tasks: tasks/common/azure_login.yml

    - name: Setup snapshot class for Velero
      include_tasks: tasks/backup/setup_snapshotclass.yml

    - name: Create Velero backup
      include_tasks: tasks/backup/create_backup.yml

