---
- name: Velero Restore Playbook
  hosts: target_cluster
  become: yes
  vars_files:
    - group_vars/all.yaml

  tasks:
    - name: Install Azure CLI on Azure hosts
      include_tasks: tasks/common/install_azure.yml
      when: cloud_provider == 'azure'
      tags: Install_Azure_CLI_on_Azure_hosts

    - name: Install full Azure CLI setup on non-Azure hosts
      include_tasks: tasks/common/install_azure_full.yml
      when: cloud_provider != 'azure'
      tags: Install_full_Azure_CLI_setup_on_non-Azure_hosts

     - name: Log in to Azure
      include_tasks: tasks/common/azure_login.yml
      tags: Log_in_to_Azure
      
    - name: Set KUBECONFIG
      include_tasks: tasks/common/set_kubeconfig_dest.yml
      tags: Set_KUBECONFIG
      
    - name: Install Velero CLI
      include_tasks: tasks/common/install_velero.yml
      tags: Install_Velero_CLI

    - name: Install Velero
      include_tasks: tasks/common/install_velero.yml
      tags: Install_Velero

    - name: Setup storage class 
      include_tasks: tasks/restore/setup_storageclass.yml
      when: cloud_provider == 'azure'
      tags: Setup_storage_class

    - name: Setup configmap
    - include_tasks: tasks/restore/setup_configmap.yml
      tags: Setup_configmap

    - name: Create Velero restore
    - include_tasks: tasks/restore/create_restore.yml
      tags: Create_Velero_restore
